######################## default configuration ####################
baseURL = "/"
title = "Crypto Travellers - Welcome to the World of Crypto"
#theme = "bookworm"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
theme = "Table-of-Content"


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


######################## Plugins ####################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#f2a900"

#################### default parameters ################################
[params]
logo = "images/crypto-travellers.png"
logo_height = "65px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Crypto Travellers"
# contact form action
contact_form_action = "#"  # contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Copyright 2021 [Cryptotravellers.com](https://cryptotravellers.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "#"
access_token = "#"

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Home"

[[menu.main]]
weight = 2
url = "/guides"
name = "Guides"

[[menu.main]]
weight = 3
url = "/reviews"
name = "Reviews"
hasChildren = true

  [[menu.main]]
  parent = "Reviews"
  weight = 1
  url = "/crypto-com-review"
  name = "Crypto.com Review"

[[menu.main]]
weight = 5
url = "#"
name = "How to Buy"
hasChildren = true

  [[menu.main]]
  parent = "How to Buy"
  weight = 1
  url = "buy-bitcoin/"
  name = "Bitcoin"

  [[menu.main]]
  parent = "How to Buy"
  weight = 2
  url = "buy-cardano/"
  name = "Cardano"

  [[menu.main]]
  parent = "How to Buy"
  weight = 3
  url = "buy-ethereum/"
  name = "Ethereum"

  [[menu.main]]
  parent = "How to Buy"
  weight = 4
  url = "buy-polkadot/"
  name = "Polkadot"

  [[menu.main]]
  parent = "How to Buy"
  weight = 5
  url = "buy-reef/"
  name = "Reef"

  [[menu.main]]
  parent = "How to Buy"
  weight = 6
  url = "buy-nexo/"
  name = "Nexo"

  [[menu.main]]
  parent = "How to Buy"
  weight = 6
  url = "buy-cro/"
  name = "CRO"



############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "about/"
name = "About"

[[menu.footer]]
weight = 2
url = "contact/"
name = "Contact"

[[menu.footer]]
weight = 3
url = "privacy-policy/"
name = "Privacy Policy"

[[menu.footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"

# Social Icons
[[params.social]]
url = "https://www.facebook.com/"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome

[[params.social]]
url = "https://www.twitter.com/"
icon = "lab la-twitter" # https://icons8.com/line-awesome

[[params.social]]
url = "https://www.instagram.com/"
icon = "lab la-instagram" # https://icons8.com/line-awesome

[[params.social]]
url = "https://www.linkedin.com/"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
